name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'deno.json'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release:')

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
